<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net5.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>list.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ExcelDataReader" Version="3.6.0" />
    <PackageReference Include="Ookii.Dialogs.Wpf" Version="4.0.0" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="4.0.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\NCRenamer\NCRenamer.csproj" />
  </ItemGroup>

</Project>
